import { Link } from 'react-router-dom';
import { LegalPageLayout } from '../../components/legal/LegalPageLayout';
import {
  COMPANY,
  PRIVACY_CONTACT_PLACEHOLDER,
  PRIVACY_EMAIL_PLACEHOLDER,
  REGISTERED_OFFICE_PLACEHOLDER,
  RETENTION_CATEGORIES,
  TECHNICAL_SERVICE_PROVIDERS,
} from '../../lib/legal/companyConfig';

export default function PrivacyPolicy() {
  return (
    <LegalPageLayout title="Privacy Policy">
      <p>
        This Privacy Policy describes how <strong>{COMPANY.legalName}</strong> (&quot;{COMPANY.shortName}&quot;,
        &quot;we&quot;, &quot;us&quot;) processes personal data through the {COMPANY.platformName} (&quot;
        {COMPANY.platformAbbrev}&quot;) web dashboard and connected mobile applications. {COMPANY.platformAbbrev} is
        intended for <strong>authorised internal use only</strong> by employees, contractors, reviewers, and other
        personnel approved by {COMPANY.shortName} in connection with {COMPANY.businessContext}.
      </p>
      <p className="text-sm text-gray-500 dark:text-gray-400 border-l-2 border-amber-500 pl-3">
        This document is provided for internal governance and user transparency. It does not constitute legal advice.
        Counsel should review before external publication or regulatory reliance.
      </p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">1. Scope and controller</h2>
      <p>
        {COMPANY.legalName} is the data controller (or equivalent role under applicable Indian law) for personal data
        processed through {COMPANY.platformAbbrev} in respect of its operations, including activities connected to{' '}
        {COMPANY.operationalRegion}. Registered office details: {REGISTERED_OFFICE_PLACEHOLDER}.
      </p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">2. Who this applies to</h2>
      <p>Authorised users may include:</p>
      <ul className="list-disc pl-5 space-y-1">
        <li>Employees and deputed staff</li>
        <li>Vigilance / operations / branch personnel</li>
        <li>Management, head office, and compliance reviewers</li>
        <li>System administrators</li>
        <li>Approved contractors or auditors with explicit access</li>
      </ul>
      <p>{COMPANY.platformAbbrev} is not offered to the general public.</p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">3. Categories of data</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li>
          <strong>Identity and account data:</strong> name, work email, phone, role, user identifiers, profile photo
          where uploaded
        </li>
        <li>
          <strong>Workforce and operational data:</strong> branch assignments, inspection submissions, checklist
          responses, remarks, risk flags, timestamps, device/app version metadata
        </li>
        <li>
          <strong>Location and field-activity data (where enabled):</strong> geofence validation, officer location
          coordinates during inspections, location pings — collected only for legitimate operational verification, not
          for unrelated or continuous off-duty tracking
        </li>
        <li>
          <strong>Evidence media:</strong> photographs and files uploaded as part of inspections
        </li>
        <li>
          <strong>Technical and security data:</strong> IP address, browser or app type, authentication logs, error
          diagnostics, audit-relevant events
        </li>
      </ul>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">4. Sources</h2>
      <p>
        Data is provided by users during authorised use, generated by the platform, or synchronised from{' '}
        {COMPANY.shortName} administrative configuration (e.g. branch master, checklist templates).
      </p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">5. Purposes and lawful basis (India)</h2>
      <p>
        Processing supports legitimate, necessary, and proportionate business purposes under the Digital Personal Data
        Protection Act, 2023 (DPDP Act), applicable IT rules, employment law, and internal policy, including:
      </p>
      <ul className="list-disc pl-5 space-y-1">
        <li>Authenticating users and enforcing role-based access</li>
        <li>Recording, reviewing, and reporting inspections and vigilance findings</li>
        <li>Escalation, SLA tracking, and management oversight</li>
        <li>Internal audit, security monitoring, fraud prevention, and incident investigation</li>
        <li>Regulatory, legal, and professional adviser requests where required</li>
        <li>Maintaining platform integrity and business continuity</li>
      </ul>
      <p>
        Where consent is required for a specific feature, it will be requested separately. Workforce location features
        must be used in line with {COMPANY.shortName} workforce notices — not for invasive or excessive surveillance.
      </p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">6. Internal monitoring and logging</h2>
      <p>
        Use of {COMPANY.platformAbbrev} may be logged (including sign-in events, configuration changes, and security
        events) for audit, access control, and misuse prevention. Monitoring is limited to what is reasonably necessary
        for internal security and compliance-support purposes.
      </p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">7. Disclosures</h2>
      <p>Personal data may be disclosed:</p>
      <ul className="list-disc pl-5 space-y-1">
        <li>Within {COMPANY.shortName} on a need-to-know basis</li>
        <li>To infrastructure providers listed in Section 8</li>
        <li>To regulators, courts, or law enforcement when required by law</li>
        <li>To auditors, advisers, or insurers under confidentiality obligations</li>
      </ul>
      <p>We do not sell personal data.</p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">8. Service providers</h2>
      <p>
        {COMPANY.shortName} uses technical providers to operate {COMPANY.platformAbbrev}. Providers evidenced in the
        current deployment include:
      </p>
      <ul className="list-disc pl-5 space-y-2">
        {TECHNICAL_SERVICE_PROVIDERS.map((p) => (
          <li key={p.name}>
            <strong>{p.name}</strong> — {p.purpose}
          </li>
        ))}
      </ul>
      <p>
        Cross-border processing may occur depending on provider regions. {COMPANY.shortName} expects appropriate
        contractual safeguards. A complete vendor register: [confirm final sub-processor list before production].
      </p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">9. Retention</h2>
      <p>
        Data is retained only as long as reasonably necessary for operational, audit, security, legal, regulatory,
        dispute-resolution, and business continuity purposes, subject to {COMPANY.shortName} records management policy
        and applicable law. The system may use soft-delete markers so historical inspection records remain auditable.
      </p>
      <ul className="list-disc pl-5 space-y-2">
        {RETENTION_CATEGORIES.map((r) => (
          <li key={r.category}>
            <strong>{r.category}:</strong> {r.description}. Retention period: {r.durationPlaceholder}.
          </li>
        ))}
      </ul>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">10. Security</h2>
      <p>
        We implement access controls, encryption in transit, database row-level security, role separation, and
        administrative safeguards appropriate to the sensitivity of financial-services operational data. No system is
        fully secure; report suspected incidents immediately.
      </p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">11. Rights and grievances</h2>
      <p>
        Data principals may have rights under the DPDP Act and other applicable law, including access, correction, and
        grievance redressal. Submit requests to:
      </p>
      <ul className="list-disc pl-5 space-y-1">
        <li>{PRIVACY_CONTACT_PLACEHOLDER}</li>
        <li>
          Interim general contact (confirm before use as grievance channel): {PRIVACY_EMAIL_PLACEHOLDER},{' '}
          {COMPANY.generalPhone}, {COMPANY.website}
        </li>
      </ul>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">12. Children</h2>
      <p>{COMPANY.platformAbbrev} is not directed at individuals under 18 years of age.</p>

      <h2 className="text-lg font-semibold text-gray-900 dark:text-white pt-4">13. Changes</h2>
      <p>
        We may update this Policy. Material changes will be communicated through the platform or internal channels.
        Continued use after notice may require renewed acknowledgement where implemented.
      </p>

      <p className="pt-4 text-sm">
        See also:{' '}
        <Link to="/legal/terms" className="text-brand-600 dark:text-brand-400 underline">
          Terms of Use
        </Link>{' '}
        and{' '}
        <Link to="/legal/acceptable-use" className="text-brand-600 dark:text-brand-400 underline">
          Acceptable Use
        </Link>
        .
      </p>
    </LegalPageLayout>
  );
}
